name: histomsc
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.8
  - numpy>=1.24.4
  - matplotlib>=3.7.5
  - openslide-python>=1.4.1
  - tqdm>=4.67.1
  - geojson>=3.1.0
  - shapely>=2.0.6
  - scikit-image>=0.21.0
  - pillow>=10.4.0
  - pytorch>=1.7.0,<3.0.0
  - pip
  - pip:
    - fastai==1.0.61
    - efficientnet-pytorch>=0.7.1
    - palettable>=3.3.3
    - KDEpy>=1.1.11
    - opencv-python>=4.10.0
    - pandas>=2.0.3
    - scipy>=1.10.1
